FROM apache/superset
USER root
RUN pip install psycopg2
USER superset
ENV SUPERSET_SECRET_KEY=secret_key
RUN superset fab create-admin \
--username admin \
--firstname Superset \
--lastname Admin \
--email admin@superset.com \
--password 123456

RUN superset db upgrade
RUN superset init


