# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/order.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/order.proto\x12\rorder_command\"\x1c\n\tExeResult\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\x07\x45xeTask\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\r\n\x0bPingRequest\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8f\x01\n\x0bPingService\x12\x41\n\x04ping\x12\x1a.order_command.PingRequest\x1a\x1b.order_command.PingResponse\"\x00\x12=\n\x07\x63ommand\x12\x16.order_command.ExeTask\x1a\x18.order_command.ExeResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.order_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXERESULT']._serialized_start=37
  _globals['_EXERESULT']._serialized_end=65
  _globals['_EXETASK']._serialized_start=67
  _globals['_EXETASK']._serialized_end=93
  _globals['_PINGREQUEST']._serialized_start=95
  _globals['_PINGREQUEST']._serialized_end=108
  _globals['_PINGRESPONSE']._serialized_start=110
  _globals['_PINGRESPONSE']._serialized_end=141
  _globals['_PINGSERVICE']._serialized_start=144
  _globals['_PINGSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
