# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import order_pb2 as protos_dot_order__pb2


class PingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_unary(
                '/order_command.PingService/ping',
                request_serializer=protos_dot_order__pb2.PingRequest.SerializeToString,
                response_deserializer=protos_dot_order__pb2.PingResponse.FromString,
                )
        self.command = channel.unary_unary(
                '/order_command.PingService/command',
                request_serializer=protos_dot_order__pb2.ExeTask.SerializeToString,
                response_deserializer=protos_dot_order__pb2.ExeResult.FromString,
                )


class PingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def command(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=protos_dot_order__pb2.PingRequest.FromString,
                    response_serializer=protos_dot_order__pb2.PingResponse.SerializeToString,
            ),
            'command': grpc.unary_unary_rpc_method_handler(
                    servicer.command,
                    request_deserializer=protos_dot_order__pb2.ExeTask.FromString,
                    response_serializer=protos_dot_order__pb2.ExeResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order_command.PingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_command.PingService/ping',
            protos_dot_order__pb2.PingRequest.SerializeToString,
            protos_dot_order__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=False,
            timeout=600,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_command.PingService/command',
            protos_dot_order__pb2.ExeTask.SerializeToString,
            protos_dot_order__pb2.ExeResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
