# Use a minimal base image for Python
FROM continuumio/miniconda3:latest

# Set working directory
WORKDIR /app

# Make RUN commands use `bash --login`:
SHELL ["/bin/bash", "--login", "-c"]

COPY mqtt.yml ./
RUN conda env create -f mqtt.yml

# Activate conda environment
ENV PATH /opt/conda/envs/aws_mqtt/bin:$PATH
RUN /bin/bash -c "source activate aws_mqtt"

# Custom entrypoint
# COPY entrypoint.sh /app
# ENTRYPOINT [ "/bin/bash","/app/entrypoint.sh" ]

# Initialize conda in bash config fiiles:
# RUN conda init bash

# RUN echo "conda activate grpc" >> ~/.bashrc

# Activate the environment, and make sure it's activated:
# Make RUN commands use the new environment:
# SHELL ["conda", "run", "-n", "landslide_ingestion", "/bin/bash", "-c"]
